spring:
  profiles:
    active: dev


---
server:
  port: 8001

mybatis:
  type-aliases-package: com.com.bingo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


Spring:
  profiles: dev
  application:
    name: springcloud-provider-dept-config # 三个名称一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qaws

eureka:
  client:
    service-url:
     defaultZone: http://e1.com:7001/eureka/,http://e2.com:7002/eureka/,http://e3.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001

info:
  app.name: 666
  company.name: 777

---
server:
  port: 8001

mybatis:
  type-aliases-package: com.com.bingo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


Spring:
  profiles: test
  application:
    name: springcloud-provider-dept-config # 三个名称一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qaws

eureka:
  client:
    service-url:
     defaultZone: http://e1.com:7001/eureka/,http://e2.com:7002/eureka/,http://e3.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001

info:
  app.name: 666
  company.name: 777