spring:
  profiles:
    active: dev

---
server:
  port: 8201
Spring:
  profiles: dev
  application:
    name: config-server-dev

eureka:
  client:
    service-url:
     defaultZone: http://e1.com:7001/eureka/,http://e2.com:7002/eureka/,http://e3.com:7003/eureka/

---
server:
  port: 8202
Spring:
  profiles: test
  application:
    name: config-server-test

eureka:
  client:
    service-url:
     defaultZone: http://e1.com:7001/eureka/,http://e2.com:7002/eureka/,http://e3.com:7003/eureka/
